# Generated by Django 5.2 on 2025-05-11 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appaccount", "0002_user_realtime_exchange_alter_userprofile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="google_uid",
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("account_type", models.CharField(default="oauth", max_length=255)),
                ("provider", models.CharField(max_length=255)),
                ("provider_account_id", models.CharField(max_length=255)),
                ("refresh_token", models.TextField(default="", max_length=255)),
                ("access_token", models.TextField(default="", max_length=255)),
                ("expires_at", models.DateTimeField(default=None, null=True)),
                ("token_type", models.CharField(default="", max_length=255)),
                ("scope", models.TextField(default="")),
                ("id_token", models.TextField(default="")),
                ("session_state", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
